### ISSUE TITLE
rundeck-ec2-nodes-plugin doesn't get task role although AWS_CONTAINER_CREDENTIALS_RELATIVE_URI is defined

### ISSUE THREAD

**Issue by doradito** [rundeck-plugins/rundeck-ec2-nodes-plugin#67]
There is a new IAM role type to use inside containers. Basically AWS configure it when AWS_CONTAINER_CREDENTIALS_RELATIVE_URI is defined in the system, but the latest rundeck-ec2-nodes-plugin version has an old version of aws-sdk, so this new feature is not supported.
```
com.amazonaws.AmazonServiceException: You are not authorized to perform this operation. (Service: AmazonEC2; Status Code: 403; Error Code: UnauthorizedOperation; Request ID: e99f4352-1857-4b43-bcac-2eb40a33e3f0)
	at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1032)
	at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:687)
	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:441)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:292)
	at com.amazonaws.services.ec2.AmazonEC2Client.invoke(AmazonEC2Client.java:9225)
	at com.amazonaws.services.ec2.AmazonEC2Client.describeInstances(AmazonEC2Client.java:4541)
	at com.dtolabs.rundeck.plugin.resources.ec2.InstanceToNodeMapper.query(InstanceToNodeMapper.java:157)
	at com.dtolabs.rundeck.plugin.resources.ec2.InstanceToNodeMapper.performQuery(InstanceToNodeMapper.java:90)
	at com.dtolabs.rundeck.plugin.resources.ec2.EC2ResourceModelSource.getNodes(EC2ResourceModelSource.java:238)
	at com.dtolabs.rundeck.core.resources.ExceptionCatchingResourceModelSource.getNodes(ExceptionCatchingResourceModelSource.java:57)
	at com.dtolabs.rundeck.core.common.ProjectNodeSupport.getNodeSet(ProjectNodeSupport.java:113)
	at com.dtolabs.rundeck.core.common.ProjectNodeSupport$ProjectNodesSource.getNodes(ProjectNodeSupport.java:327)
	at com.dtolabs.rundeck.core.resources.ExceptionCatchingResourceModelSource.getNodes(ExceptionCatchingResourceModelSource.java:57)
	at com.dtolabs.rundeck.core.resources.ResourceModelSource$getNodes.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
	at rundeck.services.nodes.CachedProjectNodes.reloadNodeSet(CachedProjectNodes.groovy:42)
	at rundeck.services.nodes.CachedProjectNodes$reloadNodeSet.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
	at rundeck.services.NodeService$_loadNodes_closure3.doCall(NodeService.groovy:261)
	at rundeck.services.NodeService$_loadNodes_closure3.doCall(NodeService.groovy)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1207)
	at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1110)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
	at groovy.lang.Closure.call(Closure.java:423)
	at groovy.lang.Closure.call(Closure.java:417)
	at com.codahale.metrics.Timer.time(Timer.java:99)
	at com.codahale.metrics.Timer$time$0.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at com.codahale.metrics.Timer$time$0.call(Unknown Source)
	at MetricswebGrailsPlugin$_addDynamicMetricMethods_closure26.doCall(MetricswebGrailsPlugin.groovy:190)
	at sun.reflect.GeneratedMethodAccessor394.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1207)
	at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1110)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
	at groovy.lang.Closure.call(Closure.java:423)
	at org.codehaus.groovy.runtime.metaclass.ClosureStaticMetaMethod.invoke(ClosureStaticMetaMethod.java:59)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoMetaMethodSiteNoUnwrap.invoke(PogoMetaMethodSite.java:230)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.call(PogoMetaMethodSite.java:68)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:124)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callSafe(AbstractCallSite.java:96)
	at rundeck.services.NodeService$_loadNodes_closure4.doCall(NodeService.groovy:268)
	at rundeck.services.NodeService$_loadNodes_closure4.doCall(NodeService.groovy)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1207)
	at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1110)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
	at groovy.lang.Closure.call(Closure.java:423)
	at groovy.lang.Closure.call(Closure.java:417)
	at groovy.lang.Closure.run(Closure.java:504)
	at org.springframework.core.task.SimpleAsyncTaskExecutor$ConcurrencyThrottlingRunnable.run(SimpleAsyncTaskExecutor.java:251)
	at java.lang.Thread.run(Thread.java:745)
```

After updating aws-sdk to  a version upper than 1.11.0, the new IAM role is supported and all start working well again.
[http://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-iam-roles.html](url)

**Comment by doradito** [comment]
Fixed at https://github.com/doradito/rundeck-ec2-nodes-plugin/compare/master...rundeck-plugins:master?expand=1

**Comment by adubkov** [comment]
I'm getting similar error now:
```
May 22 03:00:43 ERROR ExceptionCatchingResourceModelSource: [ResourceModelSource: 2.source (aws-ec2), project: cep]
May 22 03:00:43 com.amazonaws.services.ec2.model.AmazonEC2Exception: You are not authorized to perform this operation. (Service: AmazonEC2; Status Code: 403; Error Code: UnauthorizedOperation; Request ID: cfaf2183-265e-41e4-a76a-1fd4c4e2f477)
May 22 03:00:43 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1588)
May 22 03:00:43 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1258)
May 22 03:00:43 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1030)
May 22 03:00:43 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:742)
May 22 03:00:43 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:716)
May 22 03:00:43 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
May 22 03:00:43 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)
May 22 03:00:43 	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
May 22 03:00:43 	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
May 22 03:00:43 	at com.amazonaws.services.ec2.AmazonEC2Client.doInvoke(AmazonEC2Client.java:13611)
May 22 03:00:43 	at com.amazonaws.services.ec2.AmazonEC2Client.invoke(AmazonEC2Client.java:13587)
May 22 03:00:43 	at com.amazonaws.services.ec2.AmazonEC2Client.executeDescribeInstances(AmazonEC2Client.java:6590)
May 22 03:00:43 	at com.amazonaws.services.ec2.AmazonEC2Client.describeInstances(AmazonEC2Client.java:6566)
May 22 03:00:43 	at com.dtolabs.rundeck.plugin.resources.ec2.InstanceToNodeMapper.query(InstanceToNodeMapper.java:157)
May 22 03:00:43 	at com.dtolabs.rundeck.plugin.resources.ec2.InstanceToNodeMapper.performQuery(InstanceToNodeMapper.java:90)
May 22 03:00:43 	at com.dtolabs.rundeck.plugin.resources.ec2.EC2ResourceModelSource.getNodes(EC2ResourceModelSource.java:238)
May 22 03:00:43 	at com.dtolabs.rundeck.core.resources.ExceptionCatchingResourceModelSource.getNodes(ExceptionCatchingResourceModelSource.java:57)
May 22 03:00:43 	at com.dtolabs.rundeck.core.common.ProjectNodeSupport$LoadedSource.getNodes(ProjectNodeSupport.java:424)
May 22 03:00:43 	at com.dtolabs.rundeck.core.common.ProjectNodeSupport.getNodeSet(ProjectNodeSupport.java:118)
May 22 03:00:43 	at com.dtolabs.rundeck.core.common.ProjectNodeSupport$ProjectNodesSource.getNodes(ProjectNodeSupport.java:333)
May 22 03:00:43 	at com.dtolabs.rundeck.core.resources.ExceptionCatchingResourceModelSource.getNodes(ExceptionCatchingResourceModelSource.java:57)
May 22 03:00:43 	at com.dtolabs.rundeck.core.resources.ResourceModelSource$getNodes.call(Unknown Source)
May 22 03:00:43 	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
May 22 03:00:43 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
May 22 03:00:43 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117)
May 22 03:00:43 	at rundeck.services.nodes.CachedProjectNodes.reloadNodeSet(CachedProjectNodes.groovy:42)
May 22 03:00:43 	at rundeck.services.nodes.CachedProjectNodes$reloadNodeSet.call(Unknown Source)
May 22 03:00:43 	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
May 22 03:00:43 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
May 22 03:00:43 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117)
May 22 03:00:43 	at rundeck.services.NodeService$_loadNodes_closure3.doCall(NodeService.groovy:265)
May 22 03:00:43 	at rundeck.services.NodeService$_loadNodes_closure3.doCall(NodeService.groovy)
May 22 03:00:43 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
May 22 03:00:43 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
May 22 03:00:43 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
May 22 03:00:43 	at java.lang.reflect.Method.invoke(Method.java:498)
May 22 03:00:43 	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
May 22 03:00:43 	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
May 22 03:00:43 	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1218)
May 22 03:00:43 	at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1125)
May 22 03:00:43 	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1027)
May 22 03:00:43 	at groovy.lang.Closure.call(Closure.java:414)
May 22 03:00:43 	at groovy.lang.Closure.call(Closure.java:408)
May 22 03:00:43 	at com.codahale.metrics.Timer.time(Timer.java:99)
May 22 03:00:43 	at com.codahale.metrics.Timer$time$0.call(Unknown Source)
May 22 03:00:43 	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
May 22 03:00:43 	at com.codahale.metrics.Timer$time$0.call(Unknown Source)
May 22 03:00:43 	at MetricswebGrailsPlugin$_addDynamicMetricMethods_closure26.doCall(MetricswebGrailsPlugin.groovy:190)
May 22 03:00:43 	at sun.reflect.GeneratedMethodAccessor317.invoke(Unknown Source)
May 22 03:00:43 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
May 22 03:00:43 	at java.lang.reflect.Method.invoke(Method.java:498)
May 22 03:00:43 	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
May 22 03:00:43 	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
May 22 03:00:43 	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1218)
May 22 03:00:43 	at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1125)
May 22 03:00:43 	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1027)
May 22 03:00:43 	at groovy.lang.Closure.call(Closure.java:414)
May 22 03:00:43 	at org.codehaus.groovy.runtime.metaclass.ClosureStaticMetaMethod.invoke(ClosureStaticMetaMethod.java:62)
May 22 03:00:43 	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
May 22 03:00:43 	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoMetaMethodSiteNoUnwrap.invoke(PogoMetaMethodSite.java:233)
May 22 03:00:43 	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.call(PogoMetaMethodSite.java:71)
May 22 03:00:43 	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
May 22 03:00:43 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
May 22 03:00:43 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:141)
May 22 03:00:43 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callSafe(AbstractCallSite.java:101)
May 22 03:00:43 	at rundeck.services.NodeService$_loadNodes_closure4.doCall(NodeService.groovy:272)
May 22 03:00:43 	at rundeck.services.NodeService$_loadNodes_closure4.doCall(NodeService.groovy)
May 22 03:00:43 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
May 22 03:00:43 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
May 22 03:00:43 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
May 22 03:00:43 	at java.lang.reflect.Method.invoke(Method.java:498)
May 22 03:00:43 	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
May 22 03:00:43 	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
May 22 03:00:43 	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1218)
May 22 03:00:43 	at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1125)
May 22 03:00:43 	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1027)
May 22 03:00:43 	at groovy.lang.Closure.call(Closure.java:414)
May 22 03:00:43 	at groovy.lang.Closure.call(Closure.java:408)
May 22 03:00:43 	at groovy.lang.Closure.run(Closure.java:495)
May 22 03:00:43 	at org.springframework.core.task.SimpleAsyncTaskExecutor$ConcurrencyThrottlingRunnable.run(SimpleAsyncTaskExecutor.java:251)
May 22 03:00:43 	at java.lang.Thread.run(Thread.java:748)
May 22 03:00:43 WARN  LoggingResourceModelSourceCache: [ResourceModelSource: 2.source (aws-ec2), project: cep] Returning cached model data
```

Does it cache credentials anywhere temporary?

This is how it configured:
```
#resources.source.2.config.assumeRoleArn=arn\:aws\:iam\:\:XXXXX\:role/XXXX
resources.source.2.config.endpoint=ec2.eu-west-1.amazonaws.com
resources.source.2.config.httpProxyPort=80
resources.source.2.config.mappingParams=username.default\=rundeck;hostname.selector\=privateIpAddress;attributes.selector\=tags/*
resources.source.2.config.refreshInterval=60
resources.source.2.config.runningOnly=true
resources.source.2.config.useDefaultMapping=true
resources.source.2.type=aws-ec2
```

We are running rundeck inside container with external database. There is no mention about old credentials inside container, but I observing the issue when it trying to use old user credentials (it print user name in error) and not the one from `AWS_CONTAINER_CREDENTIALS_RELATIVE_URI`.

When I'm using aws sts get-caller-id i'm getting right creds.
